version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
#    ports:
#      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.21
#    volumes:
#      - /local/wordpress/nginx.conf:/etc/nginx/templates/default.conf.template
#      - /local/wordpress/certs:/etc/nginx/certs
    ports:
      - "80:80"
    restart: always
    environment:
      NGINX_HOST: http://localhost/
      NGINX_PORT: 8080
      NGINX_BACKEND_PATH: "http://wordpress"
volumes:
  db_data: {}
  wordpress_data: {}

